### PR TITLE
Adds missing imports to the sync_client template

### PR DESCRIPTION
**Pull request by hellojebus**
> [!IMPORTANT]
> Add missing imports `createBamlValidationError` and `BamlValidationError` to `sync_client.ts.j2` for error handling in `BamlSyncClient`.
> 
>   - **Imports**:
>     - Add `createBamlValidationError` and `BamlValidationError` to the import statement in `sync_client.ts.j2` from `@boundaryml/baml`.
>   - **Error Handling**:
>     - Utilize `createBamlValidationError` and `BamlValidationError` in `BamlSyncClient` for error processing.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=BoundaryML%2Fbaml&utm_source=github&utm_medium=referral)<sup> for 94cedb4f41ab3126439c13a5d73be9e610567266. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

**Comment by imalsogreg** [comment]
Thank you, nice catch! This should bring the typescript sync client into parity with the async client. Apparently we are lacking tests for error handling in the sync client.

**Review by imalsogreg — APPROVED** [review]

**Comment by hellojebus** [comment]
@imalsogreg Looking through the source helped me find the async_client, so I'm able to keep working on my project. But this is still a good catch!

**Comment by imalsogreg** [comment]
@hellojebus This is failing our CI because CI checks that the generated client code matches what's checked in.

If you can run `pnpm generate` to regenerate the client, it should pass CI. If you run into trouble, then I will do that on my side. On any new PR, we'll be sure to credit you. Thanks for finding this issue!

**Comment by hellojebus** [comment]
> @hellojebus This is failing our CI because CI checks that the generated client code matches what's checked in.
> 
> If you can run `pnpm generate` to regenerate the client, it should pass CI. If you run into trouble, then I will do that on my side. On any new PR, we'll be sure to credit you. Thanks for finding this issue!

Updated the PR, let me know if you need anything else.

**Pull request merged**
