### PR TITLE
aliased inputs

### PR DESCRIPTION
**Pull request by aaronvg**
- **Fix python types for BamlValidationError**
- **Aliased fields should render with the alias when used as function inputs**

----

> [!IMPORTANT]
> This PR updates BAML to handle aliased inputs by modifying `ArgCoercer` to use aliases and extending `BamlValidationError` with additional attributes, along with adding tests for aliased input handling.
> 
>   - **Behavior**:
>     - Update `ArgCoercer` in `to_baml_arg.rs` to use field aliases when rendering function inputs.
>     - Extend `BamlValidationError` in `baml_py.pyi` with `prompt`, `raw_output`, and `message` attributes.
>   - **Tests**:
>     - Add `aliased-inputs.baml` to test aliased input handling.
>     - Add tests in `integ-tests.test.ts` for aliased input serialization in classes, enums, and lists.
>   - **Misc**:
>     - Update `runtime_interface.rs` to pass environment values for alias resolution.
>     - Add OpenAPI paths for aliased input functions in `openapi.yaml`.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=BoundaryML%2Fbaml&utm_source=github&utm_medium=referral)<sup> for 816e6e7772b678bd1b7c228b61de0383d895abcc. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

**Comment by hellovai** [comment]
before merging this breaks somethings!

**Comment by hellovai** [comment]
e.g.:

```rust
enum Foo {
  Bar @alias('bar')
}

template_string Example(foo: Foo) #"
   {% if foo == Foo.Bar %}
   ...
   {% endif %}
"#
```


I shoudln't have to change my jinja code just cause i added aliases

**Review by hellovai — CHANGES_REQUESTED** [review]
fix broken case

**Comment by aaronvg** [comment]
Good catch, will add an integ test

**Pull request closed without merging**
