### PR TITLE
Pipenv support

### PR DESCRIPTION
**Pull request by smravec**
Added Pipenv support to the init script. New to rust so better double check it if it does not break anything

### CODE REVIEW

**Comment by aaronvg** [comment]
Thanks for the PR, we'll merge this in soon. Have you been able to get BAML up and running?

**Review by hellovai — CHANGES_REQUESTED** [review]
This looks pretty great, but can you also add a unit test to this for pyenv?

https://github.com/BoundaryML/baml/tree/canary/engine/.docker/python-tests

the run instructions are noted: https://github.com/BoundaryML/baml/blob/canary/engine/e2e_tests.py

**Comment by smravec** [comment]
Added the unit test just now

**Comment by smravec** [comment]
I was waiting for the ollama support, will try to set it up now

**Review by hellovai — APPROVED** [review]
LGTM!

**Comment by hellovai** [comment]
Hi @smravec we actually removed any need on python environments as of this point!

it now works in any python env via:
```sh
> pip install baml-py
> baml-cli init
> baml-cli generate
```

`baml-cli` is now bundled in with `baml-py` and there's no longer a dependency on our CLI which makes the installation process so much easier for users (we hope).

your PR for adding pyenv and the struggle we had with merging it in was actually a key reason why we went down this path. Glad to share more thoughts if you'd like!

**Pull request closed without merging**
